
export const windowedModules = {
    "@wordpress/a11y": "window.wp.a11y",
    "@wordpress/api-fetch": "window.wp.apiFetch",
    "@wordpress/block-editor": "window.wp.blockEditor",
    "@wordpress/blocks": "window.wp.blocks",
    "@wordpress/components": "window.wp.components",
    "@wordpress/compose": "window.wp.compose",
    "@wordpress/data": "window.wp.data",
    "@wordpress/element": "window.wp.element",
    "@wordpress/hooks": "window.wp.hooks",
    "@wordpress/i18n": "window.wp.i18n",
    "@wordpress/plugins": "window.wp.plugins",
    "@wordpress/server-side-render": "window.wp.serverSideRender",
    "@wordpress/url": "window.wp.url",
    "@wordpress/viewport": "window.wp.viewport",
    "@wordpress/edit-post": "window.wp.editPost",
    "@wordpress/edit-widgets": "window.wp.editWidgets",
    "@wordpress/editor": "window.wp.editor",
    "@wordpress/format-library": "window.wp.formatLibrary",
    "@wordpress/notices": "window.wp.notices",
    "@wordpress/nux": "window.wp.nux",
    "@wordpress/rich-text": "window.wp.richText",
    "@wordpress/token-list": "window.wp.tokenList",
    "@wordpress/date": "window.wp.date",
    "@wordpress/dom": "window.wp.dom",
    "@wordpress/keycodes": "window.wp.keycodes",
    "@wordpress/wordcount": "window.wp.wordcount",
    "@wordpress/blob": "window.wp.blob",
    "@wordpress/block-directory": "window.wp.blockDirectory",
    "@wordpress/block-library": "window.wp.blockLibrary",
  } as const;